title: Andrew Russell
description: EDS 124BR Student
site_title: 'Andrew Russell - EDS 124BR'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Cubified
email: alrussell@ucsd.edu

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 

domain: andrewlrussell.com
url: https://andrewlrussell.com
baseurl: /eds124br-portfolio
